### ISSUE TITLE
help my plugin

### ISSUE THREAD

**Issue by Vanzar** [PEMapModder/PocketMine-Plugin-Tutorials#10]
when I enter one of the players from the list this code does not work

```php
foreach($this->getConfig()->get("flyvip") as $flyvip){
					if(stripos($pm->getPlayer()->getName(), $flyvip) === false){
		          $this->a->getPlayerCor($pm);
					}
					}
```

this config.yml

```yaml
flyvip:
   pol ploy
```

**Comment by PEMapModder** [comment]
It should have a `-` in the second line in `plugin.yml`.

Next time please state how it "doesn't work".

**Comment by Vanzar** [comment]
even here the error

if($r >1){
				$this->execute($pmc);
			}

public function execute($ex){
		foreach($this->getConfig()->get("execute") as $execute){
			switch($execute){
				case "kick":
					$ex->getPlayer()->sendMessage("kick");
					break;
			}
		}
	}


[CRITICAL] Could not save Config : file_put_contents(): Filename cannot be empty
13:22:19 [CRITICAL] Could not pass event pocketmine\event\player\PlayerMoveEvent   v1.0.0: Invalid argument supplied for foreach() 
13:22:19 [WARNING] RuntimeException: "Invalid argument supplied for foreach()" (E_WARNING)

**Comment by jython234** [comment]
Do $this-saveDefaultConfig(); in your onEnable function.

**Comment by jython234** [comment]
Also, include a default config.yml in your PHAR.

**Comment by Vanzar** [comment]
@jython234 I did it all

**Comment by PEMapModder** [comment]
Please upload a zip of the full code (or link to your public repository).

**Comment by Vanzar** [comment]
@PEMapModder I solved the problem

**Comment by PEMapModder** [comment]
:)

**Comment by jython234** [comment]
:+1:
