### ISSUE TITLE
Where can I get documentation on plugin.yml?

### ISSUE THREAD

**Issue by Ivanzar** [PEMapModder/PocketMine-Plugin-Tutorials#11]
Where can I get documentation on plugin.yml?

**Comment by PEMapModder** [comment]
In the wiki of this repo.

**Comment by Ivanzar** [comment]
@PEMapModder Excuse me, but I have not found or you do not understand my question. I want to know all the functions plugin.yml

**Comment by iksaku** [comment]
Read the wiki, all the functions you need to know are explained there

**Comment by PEMapModder** [comment]
`plugin.yml` doesn't have any functions.
