### ISSUE TITLE
How to write in yml file ?

### ISSUE THREAD

**Issue by Ivanzar** [PEMapModder/PocketMine-Plugin-Tutorials#9]
This code is not work :(

```php
public function onCommand(CommandSender $cs, Command $cmd, $label, array $args){
		switch($cmd->getName()){
   case "tc":
   if(isset($args[0])){
   $cs->sendMessage("Hello " . $args[0]);
   
 $tconf->set("name:", $cs->getPlayer()->getName());
 $tconf->save();
   
   }
   break;

**Comment by PEMapModder** [comment]
Because `$tconf` is undefined?

**Comment by Vanzar** [comment]
I'm don't understand .
This is my plugin :
use pocketmine\plugin\PluginBase;
use pocketmine\utils\Config;

use pocketmine\level\Position;

use pocketmine\command\Command;
use pocketmine\command\CommandExecutor;
use pocketmine\command\CommandSender;

use pocketmine\inventory\BaseInventory;
use pocketmine\Player;
//use pocketmine\math\Vector3;

class Main extends PluginBase{
    public $tconf;
    
    public function onLoad(){
    }
    public function onEnable(){

      $this->getLogger()->info("Loading ...");
      @mkdir($this->getDataFolder());
        $this->tconf = (new Config($this->getDataFolder()."tconfig.yml", Config::YAML, array()))->getAll();
      
        $this->getLogger()->info("Done  !");
    }
    
    public function onDisable(){
        $this->getLogger()->info(Disabling ... ");
        
       $tconf = (new Config($this->getDataFolder()."tconfig.yml", Config::YAML));
       		$tconf->setAll($this->tconf);
       		$tconf->save();
    }
    
    public function onCommand(CommandSender $cs, Command $cmd, $label, array $args){
		switch($cmd->getName()){
		  case "address":
if(isset($args[0])){
		  $cs->sendMessage($cs->getPlayer($args[0])->getAddress());
		  }
		  break;
#This code is not work
   case "tc":
   if(isset($args[0])){
   $cs->sendMessage("Hello " . $args[0]);

 $tconf->set("name:", $cs->getPlayer()->getName());
 $tconf->save();

   }
   break;

     }
   
   
   
   }
    
    
    }
}
?>

**Comment by Vanzar** [comment]
This is wrong ?

**Comment by xpyctum** [comment]
@Vanzar $tconf is return all arrays in config v
Just try this
[code]
$this->tconf = new Config($this->getDataFolder()."tconfig.yml", Config::YAML);
[code]

**Comment by Vanzar** [comment]
@xpyctum  thanks

**Comment by PEMapModder** [comment]
You can also use `$this->saveDefaultConfig()` and `$this->getConfig()`. Look at the `example/ChatBlocker` directory for example.

**Comment by Vanzar** [comment]
@PEMapModder  thanks

**Comment by Vanzar** [comment]
I found the  answer

**Comment by Vanzar** [comment]
$this->tconf->set($t,array("test"=>$cs->getPlayer()->getX());
$this->tconf->save();
Thanks all

**Comment by Vanzar** [comment]
@PEMapModder I have another question. Here I have some code like this for example:
public function onBlockPlace (BlockPlaceEvent $ bp) {
if ($ bp-> getBlock () -> getID () == 35) {
$ bp-> getPlayer () -> sendMessge ("Set on X: "$ bp-> getPlayer () -> getX ()); 
}}
how to make that action is performed only after the command for example: /setb

**Comment by PEMapModder** [comment]
That is a bit more complex. I will make another example later.

**Comment by Vanzar** [comment]
Ok,but make faster, it is very interesting to me

**Comment by PEMapModder** [comment]
No, I am busy these days.

**Comment by Vanzar** [comment]
:(

**Comment by xpyctum** [comment]
@Vanzar what do you want?

**Comment by Vanzar** [comment]
@xpyctumI was just experimenting, and faced with a problem, I need it to perform the action:
public function onBlockPlace (BlockPlaceEvent $ bp) {
if ($ bp-> getBlock () -> getID () == 35) {
$ bp-> getPlayer () -> sendMessge ("Set on X: "$ bp-> getPlayer () -> getX ()); 
}} 
after the command in the example: / sb

**Comment by PEMapModder** [comment]
1. Don't separate the `$` and the variable name.
2. You better use `===` instead of `==`.
3. Connect strings with periods `.`.

**Comment by PEMapModder** [comment]
@Vanzar OK, you most likely won't understand what I am saying since I don't give an example, but I'll try.
When a player has run `/sb`, set a local field `$this->runs[$player->getId()] = true;`. Then in the event, `if(isset($this->runs[$player->getId()]))` you can know that the player has run the command. To make it only run once, `unset($this->runs[$player->getId()]);`

**Comment by Vanzar** [comment]
Sorry, it is not work :(

**Comment by mamayadesu** [comment]
Vanzar, write to onEnable() next: $this->getServer()->getPluginManager()->registerEvents($this, $this);
